### ISSUE TITLE
Extra line

### ISSUE THREAD

**Issue by baileyherbert** [ro31337/jquery.ns-autogrow#1]
I am noticing that there's an extra line being added below the text. I think an option should be added to only add a new line when it overflows.

Screenshot: https://gyazo.com/2dbbefbb092e6e9e2329379f3d320ae4

**Comment by ro31337** [comment]
Yep, will fix. Actually it's a kind of compromise: you have an extra line or you got flickering. I'll try to fix it tomorrow.

**Comment by ro31337** [comment]
@baileyherbert added a fix for that.

**Comment by baileyherbert** [comment]
Awesome, thanks for the great plugin!
