### ISSUE TITLE
Very, very slow with many textareas

### ISSUE THREAD

**Issue by vitobotta** [ro31337/jquery.ns-autogrow#13]
Hi, I am trying to use this plugin - thanks! - but I've noticed that with pages with many textareas, which normally load instantaneously, by just enabling autogrowin the same pages load in several seconds due to continuous reflow. Any idea of how to fix?

Thanks

**Comment by vitobotta** [comment]
Uhm apparently continuous reflow is triggered when setting the textarea height to the scrollHeight, even without the plugin:

``` javascript
element.height(element[0].scrollHeight)
```

Still looking into it...

**Comment by vitobotta** [comment]
Another update.... the slow part is getting the scrollHeight. IF I try setting a fixed number it's super fast.

**Comment by vitobotta** [comment]
Solved. It wasn't a problem with the plugin. Getting scrollHeight for an element is very slow because it causes a reflow, so if this is done for many textareas (in this case) too many reflows will be triggered manking the rendering very slow.

So here's what I've done in case someone else encounters the same issue: instead of enabling the plugin for each textarea at page load (which will trigger the many reflows), I enable it when clicking on the textarea:

``` javascript
    element.click ->
      $(@).autogrow({ vertical: true, horizontal: false, flickering: false })
```

Problem with this is that the textareas are not automatically resized correctly at the first page load. So to fix this I first get the scrollHeight for all the textareas and add them to a temp array, and then I set the heights for all the textareas in a second step so to cause only two reflows (one per step) instead of a reflow for each textarea:

``` javascript
      taskTitleHeights = []

      $(list).find(".task").each (index, task) ->
        taskTitleHeights.push $(task).find("#rename_task_form_title")[0].scrollHeight

      $(list).find(".task").each (index, task) ->
        $(task).find("#rename_task_form_title").height(taskTitleHeights[index])

```

This makes the page rendering very fast even with hundreds (or more) textareas while keeping the autogrow functionality. If anyone knows a better way to achieve the same please let me know. :)

**Comment by ro31337** [comment]
Great! I like to see these kind of threads! I'm happy that you were able to solve this issue!
