### ISSUE TITLE
ROWS attribute is ignored

### ISSUE THREAD

**Issue by sur1969** [ro31337/jquery.ns-autogrow#22]
ROWS attribute is ignored causing the height of the textarea to become -14.

I had to add the following code after the minHeight is set:

if (minHeight <= 0) {
    if ($e.attr('rows')  !=  undefined) {
        minHeight = $e.attr('rows') * 20;
    }
    else {
        minHeight = 20;
    }
}

**Comment by ro31337** [comment]
May I ask you for jsfiddle demo please?

**Comment by sur1969** [comment]
Looks like another library is clashing with this. Autogrow on its own works fine.

**Comment by sur1969** [comment]
Looks like it works in jsfiddle. There is probably another library clashing
with it. Will dig deeper and get back to you if necessary. In the meantime
i've closed the issue.
