### ISSUE TITLE
max height or max width grow

### ISSUE THREAD

**Issue by leizard** [ro31337/jquery.ns-autogrow#3]
Hi, thank you for great plugin. I want to set the max height or max width to grow. For example, when I use 

```
vertical : true
```

I want it ony expand to 60px height, then scroll bar will appear.
Is there any chance I can archive that ?
Thank you.

**Comment by leizard** [comment]
oh that's silly of me. I just could set the textarea max-height css attribute. thank you

**Comment by ro31337** [comment]
No problem!
