### ISSUE TITLE
vertical scroll bar flashing

### ISSUE THREAD

**Issue by ZaneCEO** [ro31337/jquery.ns-autogrow#6]
Hi, I just started to use your plugin. Good job!

The only issue I've is with the "flashing" of the vertical scrollbar. To fix it, I used:

```
textarea.autogrow {
        overflow: hidden;
}
```

Maybe you could do something like `$(element).css('overflow', 'hidden')` (implementing a proper backup + restore check) before the actual autogrow?

Thanks,

**Comment by ro31337** [comment]
Hi @ZaneCEO , did you try `flickering: false` option?

**Comment by ro31337** [comment]
btw, star it if you like it :)

**Comment by ZaneCEO** [comment]
Ouch, my bad! `flickering: false` did the trick :-)

Already star'd, of course!
